steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - europe-west3-docker.pkg.dev/$PROJECT_ID/wiki-stream-analytics/wiki-stream-analytics-producer:${_TAG}
      - .
images:
  - europe-west3-docker.pkg.dev/$PROJECT_ID/wiki-stream-analytics/wiki-stream-analytics-producer:${_TAG}
substitutions:
  _TAG: "latest"